"""
Build the qlib capability substrate (ADR 0002 Phase F / ADR 0001 Gap 2) by EXTRACTING it from the
installed qlib — never hand-written, so it can't hallucinate the very corpus meant to stop
hallucination. Run in an env that has qlib importable (here: the `qlib` conda env):

    ~/anaconda3/envs/qlib/bin/python -m agent_loop.knowledge.build

Writes operators.md, fields.md, handlers.md and README.md next to this file (metrics.md and models.md
are curated separately). Ends with a self-consistency check: every operator and $field referenced by
Alpha158/Alpha360 must be documented here — proving a factor built from documented pieces is grounded.
"""
from __future__ import annotations

import inspect
import re
from datetime import date
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROVIDER_URI = Path("~/.qlib/qlib_data/cn_data").expanduser()

_ABSTRACT = {
    "Expression", "ExpressionOps", "Feature", "PFeature", "ElemOperator", "NpElemOperator",
    "PairOperator", "NpPairOperator", "Rolling", "PairRolling", "Operators", "OpsWrapper",
    "ChangeInstrument", "Mask",  # data-plumbing, not alpha ops
}


def _provenance(kind: str) -> str:
    import qlib

    return (f"<!-- generated by agent_loop/knowledge/build.py from qlib {qlib.__version__} "
            f"on {date.today().isoformat()} ({kind}). Do not edit by hand; rerun build.py. -->\n\n")


def _category(obj) -> str:
    names = {c.__name__ for c in obj.__mro__}
    if "PairRolling" in names:
        return "rolling-pair"
    if "Rolling" in names:
        return "rolling"
    if {"PairOperator", "NpPairOperator"} & names:
        return "pair"
    return "element"


def extract_operators() -> list[tuple[str, str, str, str]]:
    from qlib.data import ops
    from qlib.data.base import Expression

    rows = []
    for name, obj in sorted(inspect.getmembers(ops, inspect.isclass)):
        if not (issubclass(obj, Expression) and obj.__module__ == "qlib.data.ops" and name not in _ABSTRACT):
            continue
        try:
            sig = str(inspect.signature(obj.__init__)).replace("self, ", "").replace("(self)", "()")
        except (ValueError, TypeError):
            sig = "(...)"
        doc = (inspect.getdoc(obj) or "").strip().splitlines()
        rows.append((name, sig, _category(obj), doc[0] if doc else ""))
    return rows


def extract_fields() -> list[str]:
    feats = PROVIDER_URI / "features"
    inst_dirs = [p for p in feats.iterdir() if p.is_dir()] if feats.exists() else []
    if not inst_dirs:
        return []
    fields = sorted({f.name.split(".")[0] for f in inst_dirs[0].glob("*.bin")})
    return fields


def extract_handlers() -> dict:
    from qlib.contrib.data.loader import Alpha158DL, Alpha360DL

    f158, n158 = Alpha158DL.get_feature_config()
    f360, n360 = Alpha360DL.get_feature_config()
    return {"a158": list(zip(n158, f158)), "a360": list(zip(n360, f360))}


def write_operators(rows) -> None:
    by_cat: dict[str, list] = {}
    for name, sig, cat, doc in rows:
        by_cat.setdefault(cat, []).append((name, sig, doc))
    labels = {"element": "Element-wise", "pair": "Pair (binary)", "rolling": "Rolling (window N)",
              "rolling-pair": "Rolling pair (two series, window N)"}
    out = [_provenance("extracted"), "# qlib expression operators\n",
           f"{len(rows)} operators usable in factor expressions. `$field` = a base field (see fields.md); "
           "`N` = an integer window. Compose freely, e.g. `Corr($close, Log($volume+1), 10)`.\n"]
    for cat in ("element", "pair", "rolling", "rolling-pair"):
        if cat not in by_cat:
            continue
        out.append(f"\n## {labels[cat]}\n\n| operator | meaning |\n|---|---|")
        for name, sig, doc in by_cat[cat]:
            out.append(f"| `{name}{sig}` | {doc} |")
    (HERE / "operators.md").write_text("\n".join(out) + "\n")


def write_fields(fields, absent_in_dataset) -> None:
    out = [_provenance("extracted"), "# Base data fields (this dataset: cn_data / csi300)\n",
           "Only these `$` fields exist in the installed dataset. **Do not reference any field not listed "
           "here.** Prefix each with `$` in expressions.\n\n"]
    out.append("| field | note |\n|---|---|")
    notes = {"open": "open price (adjusted)", "close": "close price (adjusted)", "high": "high",
             "low": "low", "volume": "volume", "factor": "adjustment factor", "change": "daily change"}
    for f in fields:
        out.append(f"| `${f}` | {notes.get(f, '')} |")
    if absent_in_dataset:
        absent = ", ".join(f"`${x}`" for x in absent_in_dataset)
        out.append(f"\n## ⚠️ Absent fields — DO NOT USE\n\n"
                   f"The stock Alpha158/Alpha360 handlers reference {absent}, but **this dataset does not "
                   f"contain {'them' if len(absent_in_dataset) > 1 else 'it'}.** Any feature or expression "
                   f"using {absent} resolves to NaN and will silently degrade the model. Avoid entirely.\n")
    out.append("\n## Label convention (from the qlib templates)\n")
    out.append("The prediction label is the 2-day-ahead forward return: `Ref($close, -2)/Ref($close, -1) - 1`. "
               "Because the label horizon is 2 days, any leakage-safe CV must embargo >= 2 days (ADR 0001 §7 v1).\n")
    (HERE / "fields.md").write_text("\n".join(out) + "\n")


def write_handlers(h, absent_in_dataset) -> None:
    a158, a360 = h["a158"], h["a360"]
    out = [_provenance("extracted"), "# Feature handlers (base feature sets to build on)\n",
           "Two ready-made handlers. The loop's base is a 20-feature subset (`ALPHA20`); when proposing, "
           "add expressions the base under-covers rather than duplicating it.\n"]
    if absent_in_dataset:
        absent = ", ".join(f"`${x}`" for x in absent_in_dataset)
        out.append(f"\n> ⚠️ Some catalog entries below reference {absent}, which is **absent from this "
                   f"dataset** (see fields.md). Those specific features resolve to NaN — do not adopt them.\n")
    out.append(f"\n## Alpha158 ({len(a158)} features) — engineered K-line / rolling factors\n")
    out.append("| name | expression |\n|---|---|")
    for nm, ex in a158:
        out.append(f"| `{nm}` | `{ex}` |")
    # Alpha360 is a mechanical Ref($field, k)/$close grid; describe the pattern + roots rather than 360 rows.
    roots = sorted({re.sub(r"\d+$", "", nm) for nm, _ in a360})
    lags = sorted({int(m.group()) for nm, _ in a360 if (m := re.search(r"\d+$", nm))})
    out.append(f"\n## Alpha360 ({len(a360)} features) — raw normalized price/volume history\n")
    out.append(f"Mechanical grid: roots `{roots}` × lag `k` in [{min(lags)}, {max(lags)}], each "
               "normalized by the latest close/volume, e.g. `CLOSE59 = Ref($close, 59)/$close`, "
               "`VOLUME5 = Ref($volume, 5)/($volume+1e-12)`. Use when you want the model to see raw history.\n")
    (HERE / "handlers.md").write_text("\n".join(out) + "\n")


def write_readme(n_ops, n_fields, h) -> None:
    import qlib

    out = [_provenance("index"), "# qlib capability substrate\n",
           "Curated, retrievable knowledge the agent reads **directly** when proposing factors/models "
           "(no embeddings/RAG — see ADR 0002 §6). Read these before authoring an expression so factors "
           "reference real operators/fields instead of invented ones.\n",
           f"\nExtracted from **qlib {qlib.__version__}**.\n",
           "\n| file | contents | source |",
           "|---|---|---|",
           f"| `operators.md` | {n_ops} expression operators + signatures | extracted from `qlib.data.ops` |",
           f"| `fields.md` | {n_fields} base `$` fields + label convention | extracted from the dataset |",
           f"| `handlers.md` | Alpha158 ({len(h['a158'])}) + Alpha360 ({len(h['a360'])}) catalogs | extracted from `qlib.contrib.data.loader` |",
           "| `metrics.md` | metric glossary + which the guardrail uses | curated |",
           "| `models.md` | model cards (LGBM + PyTorch `model.py` interface) | curated |",
           "\nRegenerate the extracted files: `~/anaconda3/envs/qlib/bin/python -m agent_loop.knowledge.build`\n"]
    (HERE / "README.md").write_text("\n".join(out) + "\n")


def _referenced(h) -> tuple[set[str], set[str]]:
    exprs = [ex for _, ex in h["a158"]] + [ex for _, ex in h["a360"]]
    ops = set(re.findall(r"([A-Z][A-Za-z]+)\(", " ".join(exprs)))
    fields = set(re.findall(r"\$([a-z]+)", " ".join(exprs)))
    return ops, fields


def main() -> None:
    rows = extract_operators()
    fields = extract_fields()
    h = extract_handlers()
    if not fields:
        raise SystemExit(f"no fields found under {PROVIDER_URI}/features — is the dataset extracted?")

    used_ops, used_fields = _referenced(h)
    op_names = {r[0] for r in rows}
    # Hard requirement: every operator the handlers use must be documented (else extraction is incomplete).
    missing_ops = used_ops - op_names
    assert not missing_ops, f"operators used by handlers but undocumented (extractor bug): {missing_ops}"
    # Soft finding: fields the handlers assume but the dataset lacks (e.g. $vwap) — a documented caveat.
    absent_fields = sorted(used_fields - set(fields))

    write_operators(rows)
    write_fields(fields, absent_fields)
    write_handlers(h, absent_fields)
    write_readme(len(rows), len(fields), h)
    print(f"[build] operators grounded: {len(used_ops)} handler ops all documented.")
    if absent_fields:
        print(f"[build] CAVEAT documented: handlers reference {absent_fields} absent from this dataset.")
    print(f"[build] wrote operators.md ({len(rows)}), fields.md ({len(fields)}), "
          f"handlers.md (A158={len(h['a158'])}, A360={len(h['a360'])}), README.md")


if __name__ == "__main__":
    main()
