"""
Build the qlib capability substrate (ADR 0002 Phase F / ADR 0001 Gap 2) by EXTRACTING it from the
installed qlib — never hand-written, so it can't hallucinate the very corpus meant to stop
hallucination. Run in an env that has qlib importable (here: the `qlib` conda env):

    ~/anaconda3/envs/qlib/bin/python -m agent_loop.knowledge.build

Writes operators.md, fields.md, handlers.md and README.md next to this file (metrics.md and models.md
are curated separately). Ends with a self-consistency check: every operator and $field referenced by
Alpha158/Alpha360 must be documented here — proving a factor built from documented pieces is grounded.
"""
from __future__ import annotations

import inspect
import re
from datetime import date
from pathlib import Path

import fire

HERE = Path(__file__).resolve().parent
PROVIDER_URI = Path("~/.qlib/qlib_data/cn_data").expanduser()

_ABSTRACT = {
    "Expression", "ExpressionOps", "Feature", "PFeature", "ElemOperator", "NpElemOperator",
    "PairOperator", "NpPairOperator", "Rolling", "PairRolling", "Operators", "OpsWrapper",
    "ChangeInstrument", "Mask",  # data-plumbing, not alpha ops
}


def _provenance(kind: str) -> str:
    import qlib

    return (f"<!-- generated by agent_loop/knowledge/build.py from qlib {qlib.__version__} "
            f"on {date.today().isoformat()} ({kind}). Do not edit by hand; rerun build.py. -->\n\n")


def _category(obj) -> str:
    names = {c.__name__ for c in obj.__mro__}
    if "PairRolling" in names:
        return "rolling-pair"
    if "Rolling" in names:
        return "rolling"
    if {"PairOperator", "NpPairOperator"} & names:
        return "pair"
    return "element"


def extract_operators() -> list[tuple[str, str, str, str]]:
    from qlib.data import ops
    from qlib.data.base import Expression

    rows = []
    for name, obj in sorted(inspect.getmembers(ops, inspect.isclass)):
        if not (issubclass(obj, Expression) and obj.__module__ == "qlib.data.ops" and name not in _ABSTRACT):
            continue
        try:
            sig = str(inspect.signature(obj.__init__)).replace("self, ", "").replace("(self)", "()")
        except (ValueError, TypeError):
            sig = "(...)"
        doc = (inspect.getdoc(obj) or "").strip().splitlines()
        rows.append((name, sig, _category(obj), doc[0] if doc else ""))
    return rows


def extract_fields(provider: str = "cn_data") -> list[str]:
    feats = Path(f"~/.qlib/qlib_data/{provider}").expanduser() / "features"
    inst_dirs = [p for p in feats.iterdir() if p.is_dir()] if feats.exists() else []
    if not inst_dirs:
        return []
    return sorted({f.name.split(".")[0] for f in inst_dirs[0].glob("*.bin")})


def extract_handlers() -> dict:
    from qlib.contrib.data.loader import Alpha158DL, Alpha360DL

    f158, n158 = Alpha158DL.get_feature_config()
    f360, n360 = Alpha360DL.get_feature_config()
    return {"a158": list(zip(n158, f158)), "a360": list(zip(n360, f360))}


def write_operators(rows) -> None:
    by_cat: dict[str, list] = {}
    for name, sig, cat, doc in rows:
        by_cat.setdefault(cat, []).append((name, sig, doc))
    labels = {"element": "Element-wise", "pair": "Pair (binary)", "rolling": "Rolling (window N)",
              "rolling-pair": "Rolling pair (two series, window N)"}
    out = [_provenance("extracted"), "# qlib expression operators\n",
           f"{len(rows)} operators usable in factor expressions. `$field` = a base field (see fields.md); "
           "`N` = an integer window. Compose freely, e.g. `Corr($close, Log($volume+1), 10)`.\n"]
    for cat in ("element", "pair", "rolling", "rolling-pair"):
        if cat not in by_cat:
            continue
        out.append(f"\n## {labels[cat]}\n\n| operator | meaning |\n|---|---|")
        for name, sig, doc in by_cat[cat]:
            out.append(f"| `{name}{sig}` | {doc} |")
    (HERE / "operators.md").write_text("\n".join(out) + "\n")


def write_fields(fields_by_ds: dict[str, list[str]], absent_by_ds: dict[str, list[str]]) -> None:
    datasets = list(fields_by_ds.keys())
    all_fields = sorted(set().union(*fields_by_ds.values())) if fields_by_ds else []
    notes = {"open": "open price (adjusted)", "close": "close price (adjusted)", "high": "high",
             "low": "low", "volume": "volume", "factor": "adjustment factor", "change": "daily change"}
    out = [_provenance("extracted"), "# Base data fields (per installed dataset)\n",
           "Reference **only** fields available in the dataset your loop runs on — availability differs by "
           "market (e.g. `cn_data` has `$change`, `us_data` does not; neither has `$vwap`). Prefix each "
           "with `$` in expressions.\n\n"]
    header = "| field | note | " + " | ".join(f"`{d}`" for d in datasets) + " |"
    out.append(header)
    out.append("|---|---|" + "|".join(["---"] * len(datasets)) + "|")
    for f in all_fields:
        avail = " | ".join("yes" if f in fields_by_ds[d] else "—" for d in datasets)
        out.append(f"| `${f}` | {notes.get(f, '')} | {avail} |")
    for d, absent in absent_by_ds.items():
        if absent:
            a = ", ".join(f"`${x}`" for x in absent)
            out.append(f"\n## ⚠️ On `{d}`: DO NOT USE {a}\n\n"
                       f"Alpha158/Alpha360 reference {a}, but `{d}` does **not** contain "
                       f"{'them' if len(absent) > 1 else 'it'}; any feature using {a} resolves to NaN and "
                       f"silently degrades the model. Avoid.\n")
    out.append("\n## Label convention (from the qlib templates)\n")
    out.append("The prediction label is the 2-day-ahead forward return: `Ref($close, -2)/Ref($close, -1) - 1`. "
               "Because the label horizon is 2 days, any leakage-safe CV must embargo >= 2 days (ADR 0001 §7 v1).\n")
    (HERE / "fields.md").write_text("\n".join(out) + "\n")


def write_handlers(h, absent_in_dataset) -> None:
    a158, a360 = h["a158"], h["a360"]
    out = [_provenance("extracted"), "# Feature handlers (base feature sets to build on)\n",
           "Two ready-made handlers. The loop's base is a 20-feature subset (`ALPHA20`); when proposing, "
           "add expressions the base under-covers rather than duplicating it.\n"]
    if absent_in_dataset:
        absent = ", ".join(f"`${x}`" for x in absent_in_dataset)
        out.append(f"\n> ⚠️ Some catalog entries below reference {absent}, which is **absent from this "
                   f"dataset** (see fields.md). Those specific features resolve to NaN — do not adopt them.\n")
    out.append(f"\n## Alpha158 ({len(a158)} features) — engineered K-line / rolling factors\n")
    out.append("| name | expression |\n|---|---|")
    for nm, ex in a158:
        out.append(f"| `{nm}` | `{ex}` |")
    # Alpha360 is a mechanical Ref($field, k)/$close grid; describe the pattern + roots rather than 360 rows.
    roots = sorted({re.sub(r"\d+$", "", nm) for nm, _ in a360})
    lags = sorted({int(m.group()) for nm, _ in a360 if (m := re.search(r"\d+$", nm))})
    out.append(f"\n## Alpha360 ({len(a360)} features) — raw normalized price/volume history\n")
    out.append(f"Mechanical grid: roots `{roots}` × lag `k` in [{min(lags)}, {max(lags)}], each "
               "normalized by the latest close/volume, e.g. `CLOSE59 = Ref($close, 59)/$close`, "
               "`VOLUME5 = Ref($volume, 5)/($volume+1e-12)`. Use when you want the model to see raw history.\n")
    (HERE / "handlers.md").write_text("\n".join(out) + "\n")


def write_readme(n_ops, fields_by_ds: dict[str, list[str]], h) -> None:
    import qlib

    ds = ", ".join(f"`{d}` ({len(f)})" for d, f in fields_by_ds.items())
    out = [_provenance("index"), "# qlib capability substrate\n",
           "Curated, retrievable knowledge the agent reads **directly** when proposing factors/models "
           "(no embeddings/RAG — see ADR 0002 §6). Read these before authoring an expression so factors "
           "reference real operators/fields instead of invented ones.\n",
           f"\nExtracted from **qlib {qlib.__version__}**. Datasets documented: {ds}.\n",
           "\n| file | contents | source |",
           "|---|---|---|",
           f"| `operators.md` | {n_ops} expression operators + signatures | extracted from `qlib.data.ops` |",
           "| `fields.md` | base `$` fields **per dataset** (cn vs us) + label convention | extracted from each dataset |",
           f"| `handlers.md` | Alpha158 ({len(h['a158'])}) + Alpha360 ({len(h['a360'])}) catalogs | extracted from `qlib.contrib.data.loader` |",
           "| `metrics.md` | metric glossary + which the guardrail uses | curated |",
           "| `models.md` | model cards (LGBM + PyTorch `model.py` interface) | curated |",
           "\nRegenerate: `~/anaconda3/envs/qlib/bin/python -m agent_loop.knowledge.build --providers cn_data,us_data`\n"]
    (HERE / "README.md").write_text("\n".join(out) + "\n")


def _referenced(h) -> tuple[set[str], set[str]]:
    exprs = [ex for _, ex in h["a158"]] + [ex for _, ex in h["a360"]]
    ops = set(re.findall(r"([A-Z][A-Za-z]+)\(", " ".join(exprs)))
    fields = set(re.findall(r"\$([a-z]+)", " ".join(exprs)))
    return ops, fields


def main(providers: str = "cn_data,us_data") -> None:
    """Regenerate the substrate. `providers` = comma-list of installed qlib datasets to document."""
    rows = extract_operators()
    h = extract_handlers()
    op_names = {r[0] for r in rows}
    used_ops, used_fields = _referenced(h)
    missing_ops = used_ops - op_names
    assert not missing_ops, f"operators used by handlers but undocumented (extractor bug): {missing_ops}"

    # fire passes a comma-list as a tuple; accept str or iterable.
    ds_names = ([p.strip() for p in providers.split(",")] if isinstance(providers, str)
                else [str(p).strip() for p in providers])
    fields_by_ds: dict[str, list[str]] = {}
    absent_by_ds: dict[str, list[str]] = {}
    for ds in (d for d in ds_names if d):
        f = extract_fields(ds)
        if not f:
            print(f"[build] skip {ds}: not installed")
            continue
        fields_by_ds[ds] = f
        absent_by_ds[ds] = sorted(used_fields - set(f))  # handler-referenced fields the dataset lacks
    if not fields_by_ds:
        raise SystemExit("no datasets found under ~/.qlib/qlib_data — is data extracted?")

    union_absent = sorted(set().union(*absent_by_ds.values()))
    write_operators(rows)
    write_fields(fields_by_ds, absent_by_ds)
    write_handlers(h, union_absent)
    write_readme(len(rows), fields_by_ds, h)
    print(f"[build] operators grounded: {len(used_ops)} handler ops all documented.")
    for ds, absent in absent_by_ds.items():
        print(f"[build] {ds}: {len(fields_by_ds[ds])} fields; absent-and-caveated: {absent}")
    print(f"[build] wrote operators.md ({len(rows)}), fields.md ({list(fields_by_ds)}), "
          f"handlers.md (A158={len(h['a158'])}, A360={len(h['a360'])}), README.md")


if __name__ == "__main__":
    fire.Fire(main)
